---
title: "Kelp morphometric properties and the link to hydrodynamic modelling"
author: "Ross Coppin"
date: "26 February 2017"
output:
  pdf_document:
    highlight: zenburn
    number_sections: yes
    toc: yes
  html_document:
    df_print: paged
    toc: yes
  word_document:
    toc: yes
bibliography: LaTeX/mycollection.bib
---

\newpage

# Summary

Marine ecosystems are maintained by a variety of complex interactions between abiotic and biotic variables such as temperature, wave exposure, pH, competition, and processes such as top-down and bottom-up control, predator-prey relationships and phenology [@Doney2012]. These abiotic and biotic variables, the interactions between them, and the various ecological processes, ultimately determine the community composition and ecological functioning of all ecosystems. Climate directly and indirectly affects the way in which abiotic and biotic variables interact, but is often compounded by other impacts such as habitat destruction, pollution, and over-fishing [@Blamey2015a]. Temperature and wave exposure have been recognised as important variables with regards to climate-driven changes within the ocean. In order to persist and survive within variable and changing environments, organisms must either migrate, adapt, or die.

Seaweeds are sessile organisms which are unable to migrate to new areas when local environmental conditions become unsuitable and therefore are forced to adapt to new conditions in order to avoid expiration. The main form of mortality for seaweeds is through mechanical dislodgment by wave action. Seaweeds, particularly brown seaweeds, are able to undergo rapid morphological adaptation to the hydrodynamic environment. This allows seaweeds to reduce mortality through mechanical dislodgement by inducing morphology which reduces overall drag. Seaweeds that are unable to avoid mechanical dislodgement either raft out to sea or wash up onto beaches. However, not all the beach-cast kelp may have originated from a nearby kelp population and may have originated from other sites or regions of the coast through rafting and ocean currents. Therefore, because kelp morphology is specific to its local environment the morphological features may be able to indicate, within a certain amount of probability, what site or region it most likely originated from. In other words, beach-cast kelp may be used as proxy for investigating the flow of  coastal currents. Using kelp as a proxy for determining its original location will be calibrated by means of a hydrodynamic model which will be designed from already existing SWAN and Delf3D models. This combined approach will allow investigation into flow regimes around the west and south-west coasts of South Africa and the role they play in sub-tidal and beach ecology. For instance, micro-plastics are recognised as a threat to marine life, however very little is known about how micro-plastics may be transported along the coast. 

The increased use of plastic in society over the past half century has resulted in large amounts of plastic litter in both the marine and terrestrial environment. The problems associated with large plastic debris have received attention for many decades, whereas those connected to marine micro-plastics comparatively received very little attention. However, today it has become a prioritized area among political organizations, agencies and NGOs around the world. The micro-plastic debris present in the ocean are derived from marine and terrestrial sources, however there is little understanding of how microplastics may be distributed with ocean currents. Therefore, the coupling of kelp morphology and the ability to simulate hydrodynamic processes can greatly improve our understanding of transport pathways and likely locations of accumulation. This in turn may inform management descions with regards to elimating and managing marine pollution in South Africa. 

\newpage

# Background

Seaweeds, browns in particular, are capable of adapting morphological characteristics to persist in changing and variable ocean environments. Changes in morphology have been shown to increase photosynthetic ability, enhance nutrient uptake, and reduce drag with regards to changes in temperature and wave exposure. Wave exposure has been shown to be an important driver of seaweed morphology, as the main mechanism of seaweed mortality is through the dislodgment. Changing morphology reduces drag and increases the probability of survival. However, locally adapted seaweed may still be dislodged in pulse disturbance events such as storms, and may raft far distances and wash up on beaches. An example would be *Ecklonia maxima* which is a conspicuous brown seaweed along the coastline and beaches around South Africa. Therefore, the beach-cast may not always originate from adjacent kelp populations but rather from other regions which the individual is adapted for. Therefore, the kelp morphology may act as a proxy for investigating coastal currents and changes thereof. The advances in ocean hydrodynamic modelling has made great progress and has been applied in a variety of ways. Therefore, this study will use advances in hydrodynamic modelling in combination with kelp morphological characteristics to investigate coastal currents. Once the model has been established it may be applied in other ways, such as investigating the transport of micorplastics along the South African coastline. The harms of microplastics to the marine environment has gained much traction in recent years, but research in South Africa is lacking. The coupling of kelp morphology and the ability to simulate hydrodynamic processes can greatly improve our understanding of transport pathways and likely locations of accumulation. This in turn may inform management decisions with regards to eliminating and managing marine pollution in South Africa.

Pollution is a huge environmental problem that affects both terrestrial and marine ecosystems. Pollution from land enters the sea where it could harm or kill marine organisms or is transported by ocean currents to other coastal areas. In these areas the pollution could re-enter the ocean or be blown by wind into terrestrail ecoystems where it could once again be ingested by oragnsims causing harm or even death. Pollution is therefore a major threat to the environment and marine organisms. In recent years the affect of microplastics on the ocean has gained much traction with scientists and politictions alike. Microplastics cosiste of tiny particles of plastic and other pollution and are thereofore are difficult to detect. Currently there is no hydrodynamic model that is able to determine dispersion, source and accumulation of microplastics along the South African coastline. Given the significant deterimental affect microplastics play in the ocean, it is important that such a mechanism be developed that will aid in better management of marine pollution in South Africa. Furthermore, this project allows for a multidicisplinery approach to be taken by combining ecology and coastal oceanography.

Abiotic and biotic factors interact in complex ways which indirectly determine behavioral and ecophysiological responses in organisms. For example, when storms or strong currents form in sub-tidal habitats, sea urchins form aggregations in order to reduce overall drag to avoid being swept away by currents. Organisms that are motile my migrate into more environmentally suitable areas when conditions become unfavorable or food sources become depleted. In changing environments migration may also allow organisms to extend their distributions. For example, ocean warming off the coast of Western Australia has allowed tropical fish species to extend their distribution into areas that were previously characterised as temperate reefs. Sessile organisms are unable to migrate into more environmentally suitable areas and are forced to either adapt or suffer expiration. Sessile organisms may respond to changing environmental conditions through changes in physiology. For example, plants may produce heat shock proteins that help buffer the affect of temperature increases. Sessile organisms may also adapt their morphology,in order to persist in changing and harsh environments, such as seaweeds.

Temperature and wave exposure have been shown to be important drivers of seaweed distribution, physiological functioning, ability to recover, population dynamics and morphology. Mechanical forces generated by the hydrodynamic environment, in the form of sudden strong ocean currents or storms, between 10- 20 m s-1 with accelerations of 400 m s-2 [@Friedland1995] are the biggest threat to kelp survival. Kelps are able to rapidly adapt their morphological characteristics to reduce drag and avoid dislodgment [@Blanchette1997]. For example a study by @Koehletal2008 showed that transplanted *Nereocystis luetkeana* plants from a wave sheltered site to a wave exposed site changed their morphology to flat blades and narrow laterals that are less prone to drag forces in 4-5 days. Another study by @FowlerWalker2006 tested for differences in morphology of *Ecklonia radiata* between wave-sheltered and wave-exposed sites and was a combination of *in situ* sampling and transplant of juvenile plants. The results showed that morphology differed between wave-sheltered and wave-exposed sites (thin thallus at sheltered sites and a narrow, thick thallus with a thick stipe at exposed sites), and was consistent with previous studies. Juveniles transplanted into wave exposed sites under went rapid morphological adaption, whilst the opposite was true for wave-sheltered sites which showed slower morphological adaption. 

Kelp morphology may be distinct to a particular region with a specific hydrodynamic environment and has the ability to raft far distances using coastal currents, and may accumulate as beach-cast in areas far from its original location. Therefore, kelp morphology may be used as a proxy for determining its original location as well as aid in characterising coastal currents. However, this approach must be combined with advances in hydrodynamic modelling for a quantitative outcome. 

Advances in numerical modelling has gained much traction in recent years and has been applied in a variety of ways with regards to ecological studies. For example, a study by @wang2009 used the Delft3D-Flow model to assess the hydraulic suitability of a stream as a spawing ground for the Chinese Sturgeon (*Acipenser sinensis*) in the Yangtze River. The authors calculated the horizontal mean vorticity which was used to assess the hydraulic environment of spawning ground. The flow field state was determined through model simulation and field-measured data used to validate the model. The results added to existing scientific database for spawning ground hydraulic environmental protection. Different numerical models can often be integrated to model across ecosystem levels. For example a study by @leon2003 used integrated physical (Delft3D hydrological model) and bio-chemical (Agricultural Non-point Source model) processes models to investigate the possible impact on the Lake Malawi water quality due to management actions performed at the watershed level.

Since wave energy is an important driver in marine ecosystems, particularly kelp, the advances in hydrodynamic modelling offer a new opportunity for multifactoral and quantitative approach to research in marine ecosystems. The Delf3D and SWAN models have been used successfully in previous studies regarding brine plume discharge, impacts of storms, affects of climate change on the hydrological environment etc. The models have not been designed for shallow environments (<6m) and therefore may not be suitable to model coastal hydrological environments. However these models may be adjusted to suit coastal waters if they are combined with a new numerical model which can be calibrated to suit these needs.

In recent years there has been growing attention on plastic pollution, particulary in the ocean. Plastic pollution can be in the form of macro- and microplastics. Microplastics are tiny plastic granuales used as scrubbers in cosmetics and air-blasting, and small plastic fragments that originate from larger pieces of plastic known as macroplastics, while macroplastics...**insert definition here**... The potential harms of  of plastic pollution in the marine environment was highlighted in the 1970's and renewed interest has lead to research showing that plastic pollution in the ocean are widespread. Plastics may become bio-available to biota in the food-web which may cause problems with an organisms physiological functioning. Furthermore, the relatively large surface area and composition of microplastics provides an environmeht that is able of adhering to organic pollutants. In other words microplastics also act as a vector for transport and assimilation of organic polluants. 

Therefore, this study not only enables research into the ecological affects of the hydrological environment on an important habitat-forming organism, it also offers the opportunity to improve on current hydrological numerical models to suit coastal environments. This in turn will allow investigation into the flow and accumulation of microplastics which are regarded as a major threat to marine life. Furthermore, the calibrated model could be applicable to other ecological studies such as dispersal of benthic flora and fauna, climate change studies, forecasting etc. 

#Kelp environmental drivers

The important environmental drivers of kelp individuals and communities include light, substrata, salinity, sedimentation, nitrients, temperature and wave exposure. Although studies have investigated the effects of important environmental drivers, the roles these factors play is often difficult to evaluate as such factors may never be fully independent of each other, i.e. environmental factors are to some extent are dependent on one another. Multifactorial studies have attempted to explain combined affects, however these studies are often limited to investigating combination of two or three environmental drivers as inclusion of too many factors can lead to results that are difficult to interept. Environmetal factors are highly variable on temporal and spatial scales and their effects may also be dependent on the life-stage of the organism, adding a further layer of complexity to investigations. 

##Light 

Light is an important factor for kelp survival, however if light is limited or excessive this may negatively impact kelp survival or growth. Much of the past research into the role light plays into the functioning of kelp [@Bruhn1996;@Belseth2012]. For instance, solar ultraviolate radiation has been shown to affect sub-canopy Ecklonia radiata sporophytes when the canopy of mature *Ecklonia radiata* was removed [@Wood1987]. The sub-canopy sporophytes experienced tissue damage,photopigment destruction,reduced growthand decreased survivorship, thus inhibiting their settlement and survival [@Wood1987]. Laboratory experiments revealed that the UV component of radiation, rather than intense radiation itself, was responsible for the effects mentioned above. High light stress has negative effects, such as photoinhibition and photo-damage on *Ecklonia cava* sporophytes [@Altamirano2004]. @Altamirano2004 found that *Ecklonia cava* is more vulnerable to light stress conditions, and less likely to recover under unfavourable conditions [@Altamirano2004]. @Bolton1985a showed that under sub-saturating irradiances and supra- optimal temperatures *Ecklonia maxima* to showed a decrease in reproductive rates and an increase in cell production. An additional finding of this study was that despite the decrease in reproductive rates, the final egge production per female was greater under these conditons. The authors interpreted this an ecological adaption that may increase survival rates under times of stress or non - ideal conditions [@Bolton1985a]. 

##Substrata
##Salinity
##Depth 

Depth does not affect kelp ecosystems directly, however a change in depth often causes fluctuations or changes in other environmental variables such as water motion, light and temperature. Water motion also decreases with depth, and some kelps better suited to deeper environments (*L. pallida*) replace those in the shallows (*E. maxima*) [@Dayton1985; @Gerard1982]. The increase in depth can lead to a decrease in sunlight penetration, with some species better adapted for low-light conditions than others, such as (*L. pallida*). Temperature may also change along a depth gradient due to a reduction in sunlight penetration [@Dayton1985; @Gerard1982]. Therefore depth does not directly play a role in kelp functioning but may alter more influential factors such as light and water motion.

##Sedimentation
##Nutrients

The importance of nutrients in the functioning of kelps is well understood [@Dayton1985; @Gaylord2012]. Dissolved nitrogen, and in particular nitrate, are important; however research has also placed emphasis on phosphate and other trace compounds for functioning of kelps [@Dayton1985]. Additionally, some kelps have the ability to store inorganic nitrogen in order to compensate for periods of low nutrient availability, which has been observed for Laminaria and Macrocystis [@Dayton1985; @Gaylord2012]. Nutrient stratification is also an important factor, particularly for canopy type kelps. The concentration of nutrients at the surface is important to the functioning and maintenance of the canopy. For instance kelp canopies in California often deteriorate in the summer months when surface nitrate levels are low [@Jackson1977]. Water motion is important in the assimilation of nutrients from the water column, and kelps have been shown to adapt blade morphology in order to create more turbulence around the boundary layer of the frond to enhance nutrient assimilation (Wheeler 1980). Temperature has also been closely linked with nutrient concentrations. Nutrients are often in higher concentrations in the water column during low temperature events. This is often an indication of an “up-welling” event, which brings cold and nutrient rich waters from the bottom to the surface of the water column. Temperature can play a direct role in the uptake of nutrients through effects on algal metabolism; however this may vary from species to species [@Raven1988]. 

##Temperature

Temperature is a driver of kelp species distributions and ecophysiological processes, as well as a lesser role in morphological adaption...**example here**...The majority of kelp species are artic and temperate organisms, and the warming of ocean temperatures is expected to cause a poleward biogeographical shift of species [@Bolton2012]. There is evidence to suggest that South African kelp forests are expanding due to ocean cooling [@Bolton2012], possibly driven by an intensification and increase in coastal upwelling [@Blamey2012, @Blamey2015a]. In South Africa there has been a biogeographical shift eastward along the coast due to a change in inshore temperature regime, making South Africa no exception to changing ocean temperatures [@Bolton2012]. Macroalgae, such as kelps, can react to an increase in surface temperatures in one of three ways: they can migrate, adapt and die [@Biskup2014]. A study by @Biskup2014 investigated the functional response of two kelp species (*Laminaria ochroleuca* and *Saccorhiza polyschides*) to rising sea temperatures. The functional responses of Saccorhiza polyschides was measured for both the subtidal and intertidal habitats, to see what affect non- optimal conditions (intertidal zone) had on the kelps [@Rinde2005]. The study found that Laminaria ochroleuca exhibited a poor ability to acclimatise and was dependent on the kelp’s life history traits [@Biskup2014]. Therefore annual kelp species are more likely to survive under non-ideal condition, and the intertidal Saccorhiza polyschides, compared to the subtidal, showed a higher physiological flexibility to changing conditions [@Biskup2014]. This may be because the intertidal zone undergoes far more change than the subtidal and therefore kelps in the intertidal are forced to adapt to harsher conditions where fluctuations in temperature, sunlight, turbidity and water motion are common. The effects on temperature have also been investigated by @Wernberg2010. The study looked at resilience of kelp beds along a latitudinal temperature gradient. Kelp abundance is likely to decline with the predicted warming of ocean waters @Wernberg2010 and although kelps have the ability to acclimatize and adjust their metabolic performance, which in turn allows them to change their physiological performance to mitigate the seasonal fluctuations in temperature, this acclimatization is done at a cost @Wernberg2010...**link to paragraph on kelp morphology**...

##Wave exposure

Other than temperature, wave exposure is also recognised as an important driver of the marine environment, and macroalgae are not exception. Wave exposure has been shown to play a role in determing distribution, abundance, diversity, composition, growth [@Cousens1982] and productivity [@pedersen2012a] of macroalgae communties. For example, the width, vertical zonation and diversity of algal communities often change predictably along gradients of wave exposure. Wave exposure may also drive macroalgae communties indirectly through the alteration in affect of another environmental driver. For instance, increasing degrees of exposure may positively influence the amount of area available to trap light on macroalgal fronds, as well as increasing nutrient uptake due to increased turbulence in the boundry layer around the frond [@lobban1994]. The most important direct effect of wave exposure on macroalgal communities is through mechanical dislodgment, which ultimately leads to expiration. Wave exposure is a complex abiotic variable which varies spatially and temporarly in the marine enviroment. Furthermore, the degree to which a macroalgae community is exposed, is dependent on local site characteristics, such as bathymetry and local wind patterns. Despite this fact, macrolagae have been able to persist in often harsh and variable wave environments. Macroalage are sessile organisms and incapabable of migrating when local conditions become unsuitable. Therefore, macroalgae must adapt to the local wave climate in order to persist and survive, and achieve this through morphological adaptation. The morphology of macroalgae are not fixed gentic traits. A study by @?? showed that *species name* was able to rapidly adapt to the local wave environment when transplanted from a low wave exposure site to a high wave exposure site. Advances in genetic techniques and taxonomy have revealed that species delination based on morphology has been inaccurate, and organisms that were once considered two seperate species are actually one species.**insert example here**. The morphological adaption that macroalgae display are therefore driven by site conditions, therefore individuals must be morphologically flexible to persist in stochastic environments. This may be achieved through different strategies and are species-specific, which can be directly attributed the high diversity in morphological characters of algal communities. For example some algae have fronds and others are articulated corraline, and therefore these species would need to adapt their morphology differently in order to persist. In general, flat strap-like blades are common in areas that are exposed to high wave energy, while at proected sites blade morphology is wide and undulated. 

@moss1948 investigated the anatomy, chemical composistion of *Fucus spiralis* at three sites that varied in wave exposure (sheltered, medium exposure and exposed). The authors found that individuals in exposed sites showed less branching of thalli as well as variation in organic nitrogen, mannitol, laminarian and alginic acid concentrations.

#Ocean and coastal waves

Regardless of the location around the world, waves are a feature of any coastline and the marine environment and are important manifestations of energy in the ocean. Waves are not the movement of water particles but is rather the movement and propagation of energy through the ocean. The source of this energy can be formed locally, such as wind-driven waves, and or from distant locations in the ocean, such as storms. This energy is then transferred from deeper water into shallower water where it plays a role in driving beach morphology. Sand and rock are eroded with each passing wave, thereby playing a role in shaping coastlines. Energy that is left-over after these processes is transferred into heat energy, and heats up the sand and rocks on which each wave hits. This energy can also be harnessed in simple ways such as a surfer catching a wave, or more complex ways such as capturing energy from the ocean environment for electricity production. However, waves are stochastic in nature and therefore the energy that propagates through the ocean is not always consistent. Therefore, it is often difficult to quantify and predict wave energy in the marine environment. Despite this fact, waves are gaining more recognition for the role they play in shaping coastlines, beaches and hence the communities and organisms that depend on these systems. 

Waves manifest themselves in different ways, which is also dependent on the energy creating force, and can be classified into different categories. For instance, "chop" are produced by local winds, while "tsunamis"" are rare waves that are formed during a earthquakes or landslides and can be produced from thousands of kilometers away. Waves in the ocean are known as "swell" and are produced from far distant storms, while the most consistent form of waves that interacts with the coastlines, usually twice a day, are called "tides". Tides are produced from differences in gravitational forces between the ocean, earth's crust, sun and the moon. These classifications can be broken down further and will be investigated later in this chapter. The focus of this chapter will be understanding wave theory and how waves form and propogate into shallow-coastal waters. This will be essential to later chapters that aim to model wave energy and callibrate the produced model with biotic parameters. 


## Generating and restoring forces

Waves are formed due to the constant interaction bewteen two forces, which are know as the "generating source" and the "restoration force". The generating force is the force which pushes water from one layer up into the other, for example pushing water up across the boundry of air. This can also occur in the ocean layers. The ocean layers through differences in desnsity, which in turn is partly driven by abiotic parameters such as temperature and salinity, which creates a boundry for wave energy to move along. Examples of such boundries are along the ocean surface, pycnoclines, and the sea-floor. **optional addition of pycnocline details**. In other words, waves occur along the boundries formed in the ocean by various abiotic processes, and therefore density boundries are essential to the propagation of energy through the ocean. 

The generating force and restoring force occur along these boundries, the generating force pushes water up across ocean boundries while the restoring force pulls it back to where the boundry was orginally, trying to restore the balance in energy. This "tug of war" between the two forces creates an oscillating motion between the boundry layers which acts as a point of disturbance, sending out energy in all directions. The disturbance energy will continue to manifest itself provided the tug and pull between the two forces is occuring. Once the generating force stops, and ultimately the energy from the point of disturbance, the waves dissipate and water restores to its orginal state. A simlple example would be blowing on water in a cup. The blowing of air onto the surface of the water in the cup creates a point of disturbance that pushes the air boundry into the water boundry. The restoring force is the surface tension of the water that is maintained through hydrogen bonds between water molecules. Once blowing on the water in the cup has stopped, the ripples or "waves" in the cup begin to diminish in size until the surface tension returns to its orginal state. The hydrogen bonds between the water molecules are stronger than the force of gravity, and therefore the force of the surface tension returns the water to its orginal state. These waves are know as "capillary waves" and is essentially residual energy after the generating source has stopped. The restoring force can also be in the form of gravity and are know as "gravity waves". Using the same example, if one blows too hard, the water boundry is pushed up into the air boundry, breaking the hydrogen bonds between water molecules which allows gravity to return the water to its orginal state. All waves in the ocean are either capillary waves or gravity waves, and their classification will be dependent on the restoring force involved. 

In nature, there are three kinds of generating forces. These are wind, displacement of large volumes of water and uneven forces of gravitational attraction bewtween the Earth, Moon and Sun. Different generating forces are associated with different wave heights, periods and the type of wave produced **insert appropriate figure**. Wind-generated waves comprise of capillary waves, chop, swell and seiche. Some seiche can form from landslides and earthquakes but most of these waves are know as a tsunami. Swell has create the waves with the large heights (up to 100m), while tides can create the tallest. 

## Wave physics and scales

Waves have a number of charateristics which are dipected in figure ??, and is an idealised representation of what a wave is. The *amplitude* is the vertical distance from its midline or *equilibrium surface* or *still water level* to its highest point known as the *crest*. The equalibrium surface is the level the ocean would be if there were no waves, for a wave to form a disturbance must occur below or above this line. The *trough* is the same distance of the amplitude, however the measurement is taken from the equilibrium surface to the lowest point. Wave height is the vertical distance from crest to trough, and is equal to twice the the amplitude. The *wavelength* is the horizontal distance from a crest/trough to the next crest/trough respectively. It is important to note that the energy progpgating from a disturbance will not reach the ocean floor in deep-water environments. The depth below a wave where the water, and anything in the water, feels no motion or disturbance is known as the *wave base*. The wave base is calculated by descending vertical from the equalibrium surface by a value equal to halve the wavelength.

As mentioned previously, the water particles in the ocean move in a circular orbit and hence return to their orginal position. This is because waves in the ocean represent moving energy, not moving water. 

##Hydrodynamic modelling

Wave exposure may be modelled through various methods which range from simple cartographic to more advanced numerical wave models. Traditional ecological measures of wave exposure usually incorportates integrative measures of hyrdodynamic conditions at a particular site. More specifically, it is the integration of mechanical processes and the influence that is has on the ecology of nearshore communities. Cartographical models can be qualitative or quantitative and were designed for the need of wave exposure measures to explain ecological distributions. A simple set of calculations on coastline and wind data, and relatively small input data sets are required. These are regarded as "fetch-based models", which measure the length of open water associated with a site along a straight line. The output of such an approach is a simplified estimate of the potential wave energy for a specific set of sites. Advances in cartographical methods using fetch-based models has allowed for wave exposure measurments for larger areas, and has been suggested as a method for predicting macroalgal community structure [@burrows2008]. An example of such a model is the "BioEx model" which was developed by @baardseth1970 to estimate wave exposure over large regions. BioEx requires frequency, strength and direction of winds, weighted by degree of exposure within various directions. BioEx is calculated as the sum of the index developed at different spatial scales (local, fjord and open). This method has been used in mapping of marine coastal biodiveristy [@Rinde2004]. @lindegarth2005 critized this approach, arguing that the choice of wave exposure method  can influence ecological inference. The authors also highlighted the need for objective, reproducible and quantitative studies comparing exposure indices [@lindegarth2005]. Other authors, such as @hill2010, have argued that these simple measures can be improved upon by including bathymetery data which allows the incorporation of diffraction into the calculation. Diffraction is topographically induced variations in wave direction. A model incorporating this complexity was developed by @isaeus2004, and is known as the "simplified wave model" (SWM). The model uses measurements of wind strength, fetch and empirically derived algorithims to mimic diffraction.

Advances in numerical modelling have been founded on physical wave theory on how a wave "behaves". This approach is based on a theoretical perspective rather than the need to answer ecological questions. Besides diffraction, these models incorporate more complexity by including wind forcing, wave-to-wave interactions and loss of energy due to friction and wave breaking. Numerical models have a variety of applications and are often incorporated within hydrodynamic general circulation models and are used operationally for forecasting the sea state [@hasselmann1988; @booij1999; @smith2001]. The downside of advanced numerical models is that are computationally intensive which creates limitations for large scale simulations. Therefore, their application along long stretches of variable coastline, inshore environments and ocean-wide simulations limited due to the poor spatial coverage. However, this models can be designed for local or site specific coverage, provided the correct data is available. 

#Aims of research

The aim of the project is to investigate coastal flow regimes along the west coast and south-west coast of South Africa and the role this may play in transport of kelp beach-cast and microplastics. This aim will be met through the following objectives:

A) Determine if the hydrodynamic environment is the main driver of kelp morphology and if this is specific to a location
B) Simulate kelp rafting by means of a hydrodynamic modelling and calibrate this model with *in situ* beach-cast morphometric data.
C) Use the calibrated hydrodynamic model to investigate dispersal of microplastics along the west coast and south-west coast of South Africa.

#References

