---
title: "Chapter 4"
author: "Ross Coppin"
date: "11/12/2020"
output: html_document
---

# Introduction

The raft-time is the amount of time macroalgae floats at the surface before becoming negatively buoyant and begins to sink to the ocean-floor. Raft-time, also referred to as raft longevity, is determined by epibiont load, macroalgal growth rate and the loss of kelp biomass over time through fragmentation. Epibiont load consists of epiphytic and bryozoan species which tend to grow more rapidly in higher light and temperature environments, such as the ocean surface [@thiel2005; @thiel2005; @graiff2016]. The increase in epibiont load reduces the buoyancy of floating macroalgal rafts over time eventually causing them to sink to the seafloor, while also potentially increasing drag [@hobday2000; @tala2013; @craw2018]. Fragmentation of kelp biomass over time may also reduce raft times further, while growth may counteract the effects of epibiont load and fragmentation provided the environmental conditions are favorable [@graiff2016; @macaya2016]. For instance a study by @rothausler2011 investigated the abiotic and biotic factors influencing raft time and dispersal potential of the giant kelp *M. pyrifera* by a combination of tethering experiments and field surveys. The results showed the physiological performance of kelp declined with increasing epiphyte biomass and that higher temperatures increased growth rate of epibionts and fragmentation of kelp. The authors concluded from the results of both the experiments and field surveys that *M. pyrifera* dispersal is dependent on low temperature and moderate irradiance conditions, with high temperatures and higher irradiance reducing overall raft-time and hence dispersal potential [@rothausler2011].


# Methods

## Raft-time

Raft-time or sometimes referred to as raft-longevity is the time a macroalgae raft remains afloat at the surface of the ocean after detachment before sinking. Raft-time was estimated from the results of past studies by @graiff2016 and @graiff2013 for each season. For summer the raft time was 25 days, winter was 38 days, and autumn was 41 days respectively. 
