---
title: "Kelp morphometric properties and its link to the hydrodynamic modelling"
author:
  name: Ross Coppin, A.J Smit and Christo Rautenbach
date: "May 2018"
output:
  word_document: default
  html_document:
    df_print: paged
  pdf_document: default
---

# Background

Marine ecosystems are maintained by a variety of complex interactions between abiotic and
biotic variables such as temperature, wave exposure, pH, competition, and processes such as top-down and bottom-up control, predator-prey relationships and phenology. These abiotic and biotic variables, the interactions between them, and the various ecological processes, ultimately determine the community composition and ecological functioning of all ecosystems. Climate directly and indirectly affects the way in which abiotic and biotic variables interact, but is often compounded by other impacts such as habitat destruction, pollution, and over-fishing. Temperature and wave exposure have been recognised as important variables with regards to climate-driven changes within the ocean. In order to persist and survive within variable and changing environments, organisms must either migrate, adapt, or die.

Seaweeds are sessile organisms which are unable to migrate to new areas when local environmental conditions become unsuitable and therefore are forced to adapt to new conditions in order to avoid expiration. The main form of mortality for seaweeds is through mechanical dislodgment by wave action. Seaweeds, particularly brown seaweeds, are able to undergo rapid morphological adaptation to the hydrodynamic environment. This allows seaweeds to reduce mortality through mechanical dislodgement by inducing morphology which reduces overall drag. Seaweeds that are unable to avoid mechanical dislodgement either raft out to sea or wash up onto beaches. However, not all the beach-cast kelp may have originated from a nearby kelp population and may have originated from other sites or regions of the coast through rafting and ocean currents. Therefore, because kelp morphology is specific to its local environment the morphological features may be able to indicate, within a certain amount of probability, what site or region it most likely originated from. In other words, beach-cast kelp may be used as proxy for investigating the flow of  coastal currents. Using kelp as a proxy for determining its original location will be calibrated by means of a hydrodynamic model which will be designed from already existing SWAN and Delf3D models. This combined approach will allow investigation into flow regimes around the west and south-west coasts of South Africa and the role they play in sub-tidal and beach ecology. For instance, micro-plastics are recognised as a threat to marine life, however very little is known about how micro-plastics may be transported along the coast. 

The increased use of plastic in society over the past half century has resulted in large amounts of plastic litter in both the marine and terrestrial environment. The problems associated with large plastic debris have received attention for many decades, whereas those connected to marine micro-plastics comparatively received very little attention. However, today it has become a prioritized area among political organizations, agencies and NGOs around the world. The micro-plastic debris present in the ocean are derived from marine and terrestrial sources, however there is little understanding of how microplastics may be distributed with ocean currents. Therefore, the coupling of kelp morphology and the ability to simulate hydrodynamic processes can greatly improve our understanding of transport pathways and likely locations of accumulation. This in turn may inform management descions with regards to elimating and managing marine pollution in South Africa. 

# Aims and objectives

The aim of the project is to investigate coastal flow regimes along the west coast and south-west coast of South Africa and the role this may play in transport of microplastics. This aim will be met through the following objectives:

1) Determine if the hydrodynamic environment is the main driver of kelp morphology and if this is specific to an area
2) Simulate kelp rafting by means of a hydrodynamic modelling and calibrate this model with *in situ* morphometric data.
3) Use calibrated hydrodynamic model to investigate dispersal of microplastics along the South African coastline.

# Methods
## Kelp morphology

Between October 2014 and April 2015, morphological measurements of *Laminaria pallida* and *Ecklonia maxima* were collected at 19 sites along the Western Cape coast of South Africa. These varying morphometrics allowed measurements such as weight, length and thickness to be compared between sites. Because the macroalgae differ in construction, species-specific morphometrics were included. These sites span across the majority of the Western Cape coast, in varying thermal and wave energy regimes. Sampling of shallower kelp individuals is currenlty taking place which will allow a deeper understanding of the hydrodynamic environment in relation to kelp morphology. 

## Hydrodynamic model

A hydrodynamic model will be developed for this study using already existing models (SWAN and Delf3d), and simulations for dispersal of kelp rafts will be performed. Morphometric measurements will be taken *in situ* after the simulation has been run in order to verify, and where neccessary, calibrate the model.

## Dispersal of microplastisics

The calibrated model will be used to simulate the dispersal of microplastics around the coast as well as to determine possible areas of accumulation. 

## Progress to date

The kelp morphometrics have already been sampled and a paper using this data is currently being written up. Morphometrics are currenlty being sampled for shallower kelp individuals (<1m), which will add to the current data set. A full proposal is also in development. 










