---
title: 'Trajectory model of passive kelp dispersal'
author: "Ross Coppin"
output:
  pdf_document:
    fig_caption: yes
  html_document:
    df_print: paged
  word_document:
    reference_docx: markdown/thesis_template.docx
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

There is a range of objects, both natural and anthropogenic, floating in the ocean of which macroalgae are regarded as one of the most important passive dispersal mechanisms of marine taxa. Floating kelp  acts as a passive dispersal mechanism for a range of marine taxa and is sometimes referred to as the 'tumble-weed' of the ocean [@edgar1987; @bushing1994; @norton1992; @helmuth1994; @holmquist1994; @smith2002; @McCormick2008]. Considerable research has been performed investigating macroalgae as a passive dispersal mechanism in the ocean, however, in recent years much of the focus has shifted towards microplastics. 

Some macroalgae species are negatively buoyant and sink to the seafloor when detached from the substrate, while other species of macroalgae have air-filled pneumatocysts or stipes which allow the plants to reach the surface where light is more abundant. In turn, the positively buoyant pneumatocysts cause plants to float to the surface when dislodged from the substratum. The structure and number of pneumatocysts varies between species. For example species from the genera *Macrocystis*, *Sargassum*, *Ascophyllum*, and *Fucus* have thalli with many small pneumatocysts, while other kelp species such as *Nereocystis luetkeana*, *Pelagophycus porra*, *Ecklonia radiata*, *Ecklonia maxima* have a single, large pneumatocysts [@dayton1985; @smith2002; @thiel2005; @graiff2016; @batista2018]. In some cases the stipe itself is air-filled, such as with *E. maxima* and *E. radiata*. Although there have been reports of floating Chlorophyta species and some Rhodophyta species, Phaeophyceae species are the most commonly reported forms of floating algae. This is most likely because the green and red species reported floating are not actually positively buoyant, but instead are kept at the surface by gas trapped inbetween or in the thalli [@dromgoole1982; @back2000]. The giant kelp *Macrocystis pyrifera* [@helmuth1994; @kingsford1995; @hobday2000; @macaya2005; @graiff2016; @batista2018] and the bull kelp *Durvillaea antarctica* [@collins2010; @tala2013 ; @tala2017; @saunders2014; @smith2002; @wichmann2012; @batista2018] have been the focus of much of the research regarding spatial and temporal dispersal patterns, the ecological role of rafting, marine connectivity and raft-time.

The raft-time is the amount of time macroalgae floats at the surface before becoming negatively buoyant and begins to sink to the ocean-floor. Raft-time, also referred to as raft longevity, is determined by epibiont load, macroalgal growth rate and the loss of kelp biomass over time through fragmentation. Epibiont load consists of epiphytic and bryozoan species which tend to grow more rapidly in higher light and temperature environments, such as the ocean surface [@thiel2005; @thiel2005; @graiff2016]. The increase in epibiont load reduces the buoyancy of floating macroalgal rafts over time eventually causing them to sink to the seafloor, while also potentially increasing drag [@hobday2000; @tala2013; @craw2018]. Fragmentation of kelp biomass over time may also reduce raft times further, while growth may counteract the effects of epibiont load and fragmentation provided the environmental conditions are favorable [@graiff2016; @macaya2016]. For instance a study by @rothausler2011 investigated the abiotic and biotic factors influencing raft time and dispersal potential of the giant kelp *M. pyrifera* by a combination of tethering experiments and field surveys. The results showed the physiological performance of kelp declined with increasing epiphyte biomass and that higher temperatures increased growth rate of epibionts and fragmentation of kelp. The authors concluded from the results of both the experiments and field surveys that *M. pyrifera* dispersal is dependent on low temperature and moderate irradiance conditions, with high temperatures and higher irradiance reducing overall raft-time and hence dispersal potential [@rothausler2011].

Many past authors have also taken various approaches to estimate not only the raft-time of macroalgal rafts but also the oceanographic influencers of macroalgae trajectory. Past research points to macroalgae trajectory being largely determined by prevailing wind conditions and surface currents [@thiel2005, @thiel2005; @hobday2000; @fraser2011; @rothausler2011; @rothausler2011]. Although ocean currents are regarded as the primary influencer, the relative importance of wind versus surface current is still not known; although the role of wind has been recognised as important in several studies. For example, a study by @harrold1989 investigated the seasonal trajectories of radio-transmitter tagged *M. pyrifera* in nearshore Monterrey Bay. The results showed that kelp rafts with little surface area exposed to the wind were largely driven by a combination of wind and wind waves, however the relative importance of wind and wind waves was not clear. In addition, the tagged kelp trajectories were more consistent with the formation of eddies during winter. Previous studies have identified wind as an important mechanism of dispersal in wind dominated ocean systems. For example the subAntartic latitudes the West Wind Drift causes continuous unidirectional surface flow and is regarded as an important potential mechanism for dispersal of floating kelp. Other studies have used genetic approaches to determine macroalgae raft trajectory characteristics by inferring source location from genetically similar populations [@nikula2013]. For example, a study by @Fraser2011 on the rafting capabilities of *Durvillaea antarctica* used a combination of population genetics and relative age estimate of ‘goosebarnacles’ attached to the raft. The presence of goosebarnacles suggests a long raft time as these species have a slow growth rate; while the genetic analyses showed these species are able to raft up to $\sim$ 390km from their local origin. The authors suggested that wind and water-movement were the primary influences of trajectory, however, this was only inferred from the genetic results and local climatology data [@fraser2011]. 

Other aspects such as buoyancy and drag also play a role in determining the trajectory and rate of transport for surface floating material. However, the past research on macroalgal trajectory has not investigated these factors which have been shown to be important aspects of trajectory for other materials such as icebergs, marine craft and microplastics. The "sail" area of an object floating at sea is the surface area exposed to the wind which results in air form drag, while the area of the object below the surface of the water is exposed to surface currents which result in water form drag. Drag coefficients related to wind and surface current have been shown to be important properties to consider when estimating trajectory and forecasting drift for search and sea rescue operations. Drag is ultimately determined by the size and shape of the object which are properties that vary considerably with macroalgae species. In addition, past research conducted within the maritime industry has shown that the size and shape of a vessel determine the relative importance of waves or wind as influencers of trajectory, as well as orientation of the object. If the length of the object is longer than the significant wave height then waves will be the primary influencer of trajectory while the opposite is true for smaller objects where the effect of waves is regarded as negligible [@breivik2011; @griffin2017]. 

Although various approaches have been used in the past to investigate floating macroalagae trajectory, very few studies have employed the use of Langrangian trajectory modelling. Furthermore, non of the existing studies using this modeling apporach have considered macroalgal morphology (i.e. shape) as an influencer on drag and ultimately trajectory. Currently, work by @Brooks2019 which investigated the effect of inertia and radial size on the trajectory of pelagic *Sargussum* rafts. The study used a custome growth model to estimate changes in biomass and ultimately radial size, while a customised Hybrid Coordinate Ocean Model (HYCOM) for the trajectory simulations was used. The results showed that trajectory of pelagic *Sargussum* was signficantly influenced by inertia and the radial size of the rafts. Langrangian trajectory modeling is a useful tool, however, the various models available often assume the object to be a spherical particle, which is obviously not the case for both biological and anthropogenic forms of marine debris in nature. The radial size included by @Brooks2019 is an improvement, however this approach does not take into account the complex morphology on an individual level into account.

To accurately determine the trajectory of marine macroalgae these aspects need to be taken into account. Past research by @plourde1999 and @breivik2008 have provided estimates of drag for various objects based on experimental work, which consisted of both direct and indirect methods of the Leeway model. However, this work does not consider biological material such as macroalgae. Although drag estimates do exist, these have been calculated for macroalgae not detached from the substratum and are regarded as fixed-point estimates. Methods used in the field of chemical engineering provide an alternative approach to estimating drag of macroalgae by means of formulae to calculate drag based on shape. Chemical engineers in the field of fluid dynamics which come across similar problems when including drag use an approach known as a 'spherecity factor'. A spherecity factor is the ratio of the surface area of a sphere having the volume as the irregular shaped particle (s) to the actual surface area of the particle (s_d) such that $$\psi=s/s_d$$. The values are dependent on the shape of the object and a range of values have been determined based on numerous experimental work. A table of various shapes and the associated spherecity factor is provided in the appendix.

There are considerable gaps in the literature with regards to macroalgae trajectory such as buoyancy, air form drag, water form drag, epibiont load, growth, fragmentation, size, shape and orientation which have not been investigated numerically in the past.  In order to determine the coefficients needed for the transport model, a series of experiments are proposed. These experiments will aim to determine aspects of buoyancy, epiphyte growth rates and transport rate, all of which have been regarded as important coefficients needed for an accurate model. The experiments will be perfomred numerically to determine the main influencers of passive solitary kelp dispersal. 

# Methods
## Model and parameterisation

Numerical calculations of particle trajectory with a Lagrangian method [@delandmeter2019], and be described by the equation

$$X(t+\Delta t) = X(t) + \int_{t}^{t+\Delta t} v(x, \tau)d \tau + \Delta X_b(t)$$
where $X$ is the three-dimensional position of a particle, $v(x,t)$ is the three-dimensional velocity field at the location in the ocean model, $X_b(t)$ is a change in position due to 'behaviour' of the particle. This can range from swimming in fish to sinking or beaching. 

The model is based on parameterisations that have been used for previous studies investigating iceberg, capsized marine vessels and microplastics. It should be noted that most of the previous studies regarding macroalgae trajectory have investigated rafts and not solitary floating individuals. A kelp raft will vary in size and can range from a few meters across to large dense mats the size of a sports field. Furthermore, some authors suggest that most macroalgae become entangled through ocean currents and not through the hydrodynamic forces that dislodge them. In addition, large kelp rafts are not a characteristics around the coast of the Cape Peninsula but rather solitary kelp are (Pers. Obs). Therefore, the trajectory of solitary *E. maxima* individuals will be considered. Previous studies have made the assumption that kelp rafts move with the same velocity as the ocean current, and instead model a ensemble of particles which trajectories are determined by a combination of ocean currents and/or the effects of winds on currents. In addition, these studies assume the particle is fully buoyant and does not vary with time.   

The the velocity of the kelp sporophyte is a function of mass and time, as the mass of the individual will vary temporarily with changes in growth rate, erosion and epibiont load (mass), which in turn will effect buoyancy and thereby the surface area exposed to wind drag and seawater drag. 

A momentum equation can be used to describe how the mass of the kelp individual changes temporarily. A previous study by @Andersson2017 who used this approach to describe the change in velocity of an iceberg over time which has been adapted to suite the current project; and taking into account the additional parameterisitions:
$$m\frac{du_i}{dt} = F_{corr} + F_{a} + F_{c} + F_{r} + F_{e}$$
where $m$ is the overall kelp mass, $u_{i}$ is the starting kelp velocity, $d$ is the distance, $F_{corr}$ is Coriolis Force, $F_{a}$ is the air drag force, $F_c$ is the seawater drag force, $F_r$ is the effect of waves on the kelp, $F_{e}$ is the epibiont load force.

The holdfast, stipe and kelp-head (fronds, primary blade and pneomatocyst) will the the focus of calculating the overall seawater drag force. Past studies refer to the surface area of the object exposed to wind forces as the "sail" area/volume, and the surface area exposed to the waves as the "keel" area/volume. The volume of the objects is required to calculate the seawater drag force and is expressed as,

$$F_{c} = F_{kelphead} +  F_{holdfast} + F_{stipekeel}$$
where $F_{c}$ is overall seawater drag force, $F_{kelphead}$ is the estimated drag coefficient for the top portion of the plant (fronds, primary blade, pnuematocyst), $V_{holdfast}$ is the estimated drag coefficient for the holdfast, $V_{stipekeel}$ is the estimated drag coefficient for the volume of the stipe submerged. The assumption made is that the kelp-head and holdfast will not change in volume while floating and that the entire holdfast will be submerged. Provided the exposed volume of the kelp exposed to the air is know the submerged portion $V_{stipekeel}$ and overall mass can be calculated based on Archimedes law [@Andersson2017]:
$$V_{stipekeel} = V_{stipesail}\frac{p_{ice}}{p_w-p_{ice}}$$

and so,
$$m = (V_{stipesail}+V_{stipekeel})p_{ice} =(1 + \frac{p_w}{p_w -p{ice}})V_{stipesail}p_{ice}$$
To calculate the volume of the stipe a idealised cyliderical form is used with height being subsituted for height such that:
$$V = \pi r^2 l$$

# Results

# Discussion

# Appendix

Insert table of spherecity factors. 

