---
title: "Paper summaries"
output: html_notebook
---

# @Cavanaugh2011

In southern California, growth is fastest in winter and spring when nutrient levels are high and competition for light and space is low (due to low algal biomass), and slowest during summer when nutrients are low and competition for light and space is high due to well-developed algal canopies (Zimmer- man & Kremer 1986, Reed et al. 2008). The relatively low capacity of giant kelp to store nutrients (~30 d, Zimmerman & Kremer 1986) causes populations to respond rapidly to fluctuations in nutrient supply. Much like growth, the recruitment of giant kelp in southern California and elsewhere responds strongly to fluctuations in nutrients and light as determined by biotic and abiotic processes (Dayton et al. 1984, Reed & Foster 1984, Reed et al. 2008)

Giant-kelp mortality occurs in the form of senes- cence, grazing, and wave-driven disturbance (Graham et al. 2007). Reed et al. (2008) found that both frond losses and plant mortality were correlated to wave heights in kelp forests near Santa Barbara, California, although correlations were stronger at the plant level. High mortality can also result from prolonged con - ditions of low nutrients such as those associated with El Niño events (Dayton & Tegner 1990, Dayton et al. 1999, Edwards 2004). The biomass dynamics of giant kelp reflect the interplay of these physical and bio - logical forcings that control patterns of recruitment, growth, and mortality.

The relative importance of resource availability (light and nutrients) versus physical disturbance (waves) in controlling the biomass dynamics of giant kelp remains an open question. For example, Dayton et al. (1999) found that large-scale, low-frequency changes in nutrient availability had the largest effects on kelp populations in San Diego; however, recent analyses of kelp forests in central and southern California during 2001 to 2009 (a period lacking any major nutrient-poor El Niño conditions) showed that wave disturbance ex - plained more variability in kelp biomass and produc- tion than either nutrient availability or grazing (Reed et al. 2008, D. C. Reed et al. unpubl.). It is clear that the apparent influence that each of these physical forcings has on kelp populations is dependent on the spatial and temporal scales of observation (Edwards 2004).

While a particular kelp forest may be nutrient-limited at a given time, another forest in a more nutrient-rich region may have its dynamics controlled by wave dis- turbance. The vast majority of long-term kelp studies have been made at the local scale (<500 m2) and so it has been difficult to test how their conclusions apply to larger areas (>1 km2)


